### ISSUE TITLE
When the Receive function is called ?

### ISSUE THREAD

**Issue by papanada** [shamique/simple_chat_applcation#1]
Hi I'm using your app in ionic 4 and all works. But the client doesn't receive messages because Receive function isn't called anywhere.

**Comment by shamique** [comment]
Hi,

Receive function should called inside the constructor method. Call `this.Receive();` function after the socket is initialize. 

Check [`home.ts`](https://github.com/shamique/simple_chat_applcation/blob/master/src/pages/home/home.ts) file. 

Thanks
